# Generated by Django 4.2.3 on 2024-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='worker_photos')),
                ('work_experience', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'ordering': ['created_at', 'work_experience'],
            },
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
