# Generated by Django 4.2.3 on 2024-06-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_worker_delete_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название услуги', max_length=100, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите стоимость услуги', max_digits=8, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name', 'price'],
            },
        ),
        migrations.AlterField(
            model_name='worker',
            name='lastname',
            field=models.CharField(blank=True, help_text='Введите отчество работника', max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(help_text='Введите имя работника', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(help_text='Введите номер работника', max_length=12, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(help_text='Загрузите фото работника', upload_to='worker_photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(help_text='Введите фамилию работника', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_experience',
            field=models.IntegerField(help_text='Введите рабочий опыт работника', verbose_name='Опыт работы'),
        ),
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Введите фамилию и имя клиента', max_length=100, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(help_text='Введите номер телефона клиента', max_length=12, verbose_name='Мобильный телефон клиента')),
                ('date', models.DateField(help_text='Выберите дату приёма', verbose_name='Дата')),
                ('time', models.TimeField(help_text='Выберите время приёма', verbose_name='Время')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите итоговую стоимость за приём', max_digits=8, verbose_name='Итоговая цена')),
                ('service', models.ForeignKey(help_text='Выберите услуги', on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Услуга')),
                ('worker', models.ForeignKey(help_text='Выберите работника', on_delete=django.db.models.deletion.CASCADE, to='main.worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['date', 'time', 'worker'],
            },
        ),
    ]
