# Generated by Django 4.2.3 on 2024-06-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_alter_worker_lastname_alter_worker_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visiting',
            name='service',
        ),
        migrations.AddField(
            model_name='visiting',
            name='service',
            field=models.ManyToManyField(help_text='Выберите услуги', to='main.service', verbose_name='Услуга'),
        ),
    ]
