# Generated by Django 4.2.3 on 2024-06-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_worker_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiting',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Введите фамилию и имя клиента', max_length=100, null=True, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Введите номер телефона клиента', max_length=12, null=True, verbose_name='Мобильный телефон клиента'),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='service',
            field=models.ManyToManyField(blank=True, help_text='Выберите услуги', null=True, to='main.service', verbose_name='Услуга'),
        ),
    ]
