# Generated by Django 4.2.3 on 2024-06-28 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_visiting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiting',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='main.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, help_text='Введите имя работника', max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
