# Generated by Django 4.2.3 on 2024-06-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_visiting_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiting',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.worker', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(help_text='Введите имя работника', max_length=50, verbose_name='Имя'),
        ),
    ]
