# Generated by Django 4.2.3 on 2024-06-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_visiting_worker_alter_worker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiting',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker', verbose_name='Работник'),
        ),
    ]
